(in-package :cl-user)

(defpackage :monkeylib-gsuite
  (:use
   :cl
   :drakma
   :monkeylib-utilities
   :monkeylib-json
   :monkeylib-json-parser)
  (:export
   :document-create
   :document-get
   :document-batch-update
   :append-to-doc

   :make-update-text-style-request
   :make-update-paragraph-style-request
   :grey

   ;; schemas.lisp
   :%list
   :auto-text
   :background
   :background-suggestion-state
   :batch-update-document-request
   :batch-update-document-response
   :body
   :bullet
   :bullet-suggestion-state
   :color
   :column-break
   :create-footer-request
   :create-footer-response
   :create-footnote-request
   :create-footnote-response
   :create-header-request
   :create-header-response
   :create-named-range-request
   :create-named-range-response
   :create-paragraph-bullets-request
   :crop-properties
   :crop-properties-suggestion-state
   :delete-content-range-request
   :delete-footer-request
   :delete-header-request
   :delete-named-range-request
   :delete-paragraph-bullets-request
   :delete-positioned-object-request
   :delete-table-column-request
   :delete-table-row-request
   :dimension
   :document
   :document-style
   :document-style-suggestion-state
   :embedded-drawing-properties
   :embedded-drawing-properties-suggestion-state
   :embedded-object
   :embedded-object-border
   :embedded-object-border-suggestion-state
   :embedded-object-suggestion-state
   :end-of-segment-location
   :equation
   :footer
   :footnote
   :footnote-reference
   :header
   :horizontal-rule
   :image-properties
   :image-properties-suggestion-state
   :inline-object
   :inline-object-element
   :inline-object-properties
   :inline-object-properties-suggestion-state
   :insert-inline-image-request
   :insert-inline-image-response
   :insert-inline-sheets-chart-response
   :insert-page-break-request
   :insert-section-break-request
   :insert-table-column-request
   :insert-table-request
   :insert-table-row-request
   :insert-text-request
   :link
   :linked-content-reference
   :linked-content-reference-suggestion-state
   :list-properties
   :list-properties-suggestion-state
   :location
   :merge-table-cells-request
   :named-range
   :named-ranges
   :named-style
   :named-style-suggestion-state
   :named-styles
   :named-styles-suggestion-state
   :nesting-level
   :nesting-level-suggestion-state
   :object-references
   :optional-color
   :page-break
   :paragraph
   :paragraph-border
   :paragraph-element
   :paragraph-style
   :paragraph-style-suggestion-state
   :person
   :person-properties
   :positioned-object
   :positioned-object-positioning
   :positioned-object-positioning-suggestion-state
   :positioned-object-properties
   :positioned-object-properties-suggestion-state
   :range
   :replace-all-text-request
   :replace-all-text-response
   :replace-image-request
   :replace-named-range-content-request
   :request
   :response
   :rgb-color
   :section-break
   :section-column-properties
   :section-style
   :shading
   :shading-suggestion-state
   :sheets-chart-reference
   :sheets-chart-reference-suggestion-state
   :size
   :size-suggestion-state
   :structural-element
   :substring-match-criteria
   :suggested-bullet
   :suggested-document-style
   :suggested-inline-object-properties
   :suggested-list-properties
   :suggested-named-styles
   :suggested-paragraph-style
   :suggested-positioned-object-properties
   :suggested-table-cell-style
   :suggested-table-row-style
   :suggested-text-style
   :tab-stop
   :table
   :table-cell
   :table-cell-border
   :table-cell-location
   :table-cell-style
   :table-cell-style-suggestion-state
   :table-column-properties
   :table-of-contents
   :table-range
   :table-row
   :table-row-style
   :table-row-style-suggestion-state
   :table-style
   :text-run
   :text-style
   :text-style-suggestion-state
   :unmerge-table-cells-request
   :update-document-style-request
   :update-paragraph-style-request
   :update-section-style-request
   :update-table-cell-style-request
   :update-table-column-properties-request
   :update-table-row-style-request
   :update-text-style-request
   :weighted-font-family
   :write-control))
